services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
        POSTGRES_USER: ${POSTGRES_USER} 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    hostname: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
